export const countryCodes = [
  'MA', 'BT', 'UA', 'GI', 'QA', 'AW', 'VN', 'IQ', 'MQ', 'CY', 'ZW', 'CZ', 'FR', 'SE', 'LK', 'AO', 'HU',
  'PL', 'PA', 'ZA', 'ML', 'SG', 'ES', 'MC', 'MT', 'CD', 'UY', 'AM', 'KP', 'ME', 'TZ', 'AR', 'BG', 'FI', 'MR',
  'MX', 'ET', 'LV', 'CU', 'UM', 'SA', 'TT', 'BE', 'SN', 'MO', 'KW', 'RO', 'KH', 'LR', 'PK', 'GB', 'BB', 'BO', 'AE',
  'LY', 'TF', 'CA', 'RS', 'TJ', 'AZ', 'NI', 'GN', 'AT', 'GT', 'PG', 'CG', 'KR', 'AL', 'IT', 'LU', 'GE',
  'GR', 'KG', 'BM', 'EG', 'UZ', 'IE', 'ID', 'KE', 'TN', 'DK', 'AU', 'VE', 'HK', 'CH', 'RU', 'NL', 'CL', 'MD', 'DE',
  'PS', 'IL', 'NZ', 'LT', 'PR', 'BY', 'KY', 'GH', 'PE', 'BW', 'BR', 'BD', 'CM', 'SO', 'DO', 'CR', 'CO', 'PH', 'NO',
  'RW', 'BF', 'TD', 'BN', 'AQ', 'IN', 'WS', 'LB', 'DZ', 'MM', 'IR', 'MN', 'PY', 'SV', 'SI', 'BS', 'NP', 'IS',
  'EC', 'PF', 'HN', 'KZ', 'BA', 'CI', 'EE', 'US', 'AF', 'MK', 'TR', 'TW', 'LI', 'CN', 'MY', 'PT', 'JM', 'NA', 'NG',
  'UG', 'SK', 'TH', 'MG', 'SY', 'JO', 'LA', 'HR', 'JP'
];

/**
 * This function takes a country code and returns the corresponding country name.
 */
const countryCodeToName: Record<string, string> = {
  MA: 'Morocco',
  BT: 'Bhutan',
  UA: 'Ukraine',
  GI: 'Gibraltar',
  QA: 'Qatar',
  AW: 'Aruba',
  VN: 'Vietnam',
  IQ: 'Iraq',
  MQ: 'Martinique',
  CY: 'Cyprus',
  ZW: 'Zimbabwe',
  CZ: 'Czech Republic',
  FR: 'France',
  SE: 'Sweden',
  LK: 'Sri Lanka',
  AO: 'Angola',
  HU: 'Hungary',
  PL: 'Poland',
  PA: 'Panama',
  ZA: 'South Africa',
  ML: 'Mali',
  SG: 'Singapore',
  ES: 'Spain',
  MC: 'Monaco',
  MT: 'Malta',
  CD: 'Congo (Kinshasa)',
  UY: 'Uruguay',
  AM: 'Armenia',
  KP: 'North Korea',
  ME: 'Montenegro',
  TZ: 'Tanzania',
  AR: 'Argentina',
  BG: 'Bulgaria',
  FI: 'Finland',
  MR: 'Mauritania',
  MX: 'Mexico',
  ET: 'Ethiopia',
  LV: 'Latvia',
  CU: 'Cuba',
  UM: 'United States Minor Outlying Islands',
  SA: 'Saudi Arabia',
  TT: 'Trinidad and Tobago',
  BE: 'Belgium',
  SN: 'Senegal',
  MO: 'Macau',
  KW: 'Kuwait',
  RO: 'Romania',
  KH: 'Cambodia',
  LR: 'Liberia',
  PK: 'Pakistan',
  GB: 'United Kingdom',
  BB: 'Barbados',
  BO: 'Bolivia',
  AE: 'United Arab Emirates',
  LY: 'Libya',
  TF: 'French Southern Territories',
  CA: 'Canada',
  RS: 'Serbia',
  TJ: 'Tajikistan',
  AZ: 'Azerbaijan',
  NI: 'Nicaragua',
  GN: 'Guinea',
  AT: 'Austria',
  GT: 'Guatemala',
  PG: 'Papua New Guinea',
  CG: 'Congo (Brazzaville)',
  KR: 'South Korea',
  AL: 'Albania',
  IT: 'Italy',
  LU: 'Luxembourg',
  GE: 'Georgia',
  GR: 'Greece',
  KG: 'Kyrgyzstan',
  BM: 'Bermuda',
  EG: 'Egypt',
  UZ: 'Uzbekistan',
  IE: 'Ireland',
  ID: 'Indonesia',
  KE: 'Kenya',
  TN: 'Tunisia',
  DK: 'Denmark',
  AU: 'Australia',
  VE: 'Venezuela',
  HK: 'Hong Kong',
  CH: 'Switzerland',
  RU: 'Russia',
  NL: 'Netherlands',
  CL: 'Chile',
  MD: 'Moldova',
  DE: 'Germany',
  PS: 'Palestine',
  IL: 'Israel',
  NZ: 'New Zealand',
  LT: 'Lithuania',
  PR: 'Puerto Rico',
  BY: 'Belarus',
  KY: 'Cayman Islands',
  GH: 'Ghana',
  PE: 'Peru',
  BW: 'Botswana',
  BR: 'Brazil',
  BD: 'Bangladesh',
  CM: 'Cameroon',
  SO: 'Somalia',
  DO: 'Dominican Republic',
  CR: 'Costa Rica',
  CO: 'Colombia',
  PH: 'Philippines',
  NO: 'Norway',
  RW: 'Rwanda',
  BF: 'Burkina Faso',
  TD: 'Chad',
  BN: 'Brunei',
  AQ: 'Antarctica',
  IN: 'India',
  WS: 'Samoa',
  LB: 'Lebanon',
  DZ: 'Algeria',
  MM: 'Myanmar',
  IR: 'Iran',
  MN: 'Mongolia',
  PY: 'Paraguay',
  SV: 'El Salvador',
  SI: 'Slovenia',
  BS: 'Bahamas',
  NP: 'Nepal',
  IS: 'Iceland',
  EC: 'Ecuador',
  PF: 'French Polynesia',
  HN: 'Honduras',
  KZ: 'Kazakhstan',
  BA: 'Bosnia and Herzegovina',
  CI: 'Ivory Coast',
  EE: 'Estonia',
  US: 'United States',
  AF: 'Afghanistan',
  MK: 'North Macedonia',
  TR: 'Turkey',
  TW: 'Taiwan',
  LI: 'Liechtenstein',
  CN: 'China',
  MY: 'Malaysia',
  PT: 'Portugal',
  JM: 'Jamaica',
  NA: 'Namibia',
  NG: 'Nigeria',
  UG: 'Uganda',
  SK: 'Slovakia',
  TH: 'Thailand',
  MG: 'Madagascar',
  SY: 'Syria',
  JO: 'Jordan',
  LA: 'Laos',
  HR: 'Croatia',
  JP: 'Japan'
};

const countryNameToCode: Record<string, string> = Object.entries(countryCodeToName).reduce(
  (acc, [code, name]) => {
    acc[name] = code;
    return acc;
  },
  {} as Record<string, string>
);

/**
 * This function takes a country name and returns the corresponding country code.
 * @param countryName - The country name to look up.
 */
export function getCountryCodeByName(countryName: string): string | undefined {
  return countryNameToCode[countryName];
}

/**
 * 
 * This function takes a country code and returns the corresponding country name.
 * @param countryCode - The country code to look up.
 */
export function getCountryNameByCode(countryCode: string): string | undefined {
  return countryCodeToName[countryCode];
}